setTimeout(()=>{
    document.getElementById("timer").innerText=10;
    setTimeout(()=>{
        document.getElementById("timer").innerText=9;
        setTimeout(()=>{
            document.getElementById("timer").innerText=8;
            setTimeout(()=>{
                document.getElementById("timer").innerText=7;
                setTimeout(()=>{
                    document.getElementById("timer").innerText=6;
                    setTimeout(()=>{
                        document.getElementById("timer").innerText=5;
                        setTimeout(()=>{
                            document.getElementById("timer").innerText=4;
                            setTimeout(()=>{
                                document.getElementById("timer").innerText=3;
                                setTimeout(()=>{
                                    document.getElementById("timer").innerText=2;
                                    setTimeout(()=>{
                                        document.getElementById("timer").innerText=1;
                                        setTimeout(()=>{
                                            document.getElementById("timer").innerText="Happy Independence Day 🎉!!";
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
})